---
version: 2
updates:

  # Enable version updates for Python
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "*"
        dependency-type: "all"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "Type: Dependencies"
      - "Lang: Dockerfile"

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Europe/Madrid"
