---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        exclude: "devcontainer.json"
      - id: pretty-format-json
        exclude: "devcontainer.json"
        args:
          - --autofix
          - --no-sort-keys
          - --indent=4

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.23
    hooks:
      - id: pymarkdown
        pass_filenames: false
        args:
          - --config
          - docs/appcc/clean.json
          - scan
          - ./docs/appcc/src

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-mkdocs
          - mdformat-tables
          - mdformat-frontmatter
          - mdformat-admon
          - mdformat-wikilink

  - repo: local
    hooks:
      - id: taplo-lint
        name: taplo lint
        entry: taplo check
        language: system
        types: [toml]
      - id: taplo-format
        name: taplo format
        entry: taplo format
        language: system
        types: [toml]
        args:
          - --option
          - array_auto_expand=true
          - --option
          - array_trailing_comma=true
          - --option
          - align_entries=true
          - --option
          - column_width=0
          - --option
          - indent_entries=true
          - --option
          - reorder_arrays=true

  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.0-beta
    hooks:
      - id: hadolint
