---
name: Actions CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  lint-actions:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint GitHub Actions
        uses: eifinger/actionlint-action@v1
