---
name: Container CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  TEST_TAG: ${{ github.repository }}:test
  LATEST_TAG: ${{ github.repository }}:test

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Get Python Version
        id: python
        run: echo "version=$(cat .python-version)" >> "$GITHUB_OUTPUT"

      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          tags: ${{ env.TEST_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            REPOSITORY=${{ github.repository }}
            PYTHON_VERSION=${{ steps.python.outputs.version }}
          outputs: type=docker,dest=${{ github.workspace }}/image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: ${{github.workspace}}/image.tar

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download image
        uses: actions/download-artifact@v4
        with:
          name: image

      - name: Load image
        run:  docker load --input ${{github.workspace}}/image.tar

      - name: Run Test Image
        run:  docker run -d --name test-container -p 8080:80 ${{ env.TEST_TAG }}

      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: http://localhost:8080
          max-attempts: 3
