---
name: Container CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Get Python Version
        id: python
        run: echo "version=$(cat .python-version)" >> "$GITHUB_OUTPUT"

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          file: ./Dockerfile
          tags: ${{ github.repository }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            REPOSITORY=${{ github.repository }}
            PYTHON_VERSION=${{ steps.python.outputs.version }}

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      docs:
        image: ${{ github.repository }}:latest
        env:
          NGINX_PORT: "8080"
          NGINX_HOST: "docs"
        ports:
          - 8080:8080

    steps:
    - name: Test Site
      uses: jtalk/url-health-check-action@v4
      with:
        url: http://localhost:${{ job.services.docs.ports[8080] }}
        max-attempts: 3 # Optional, defaults to 1
        retry-all: true
