---
name: Container CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  container:
    runs-on: ubuntu-latest

    needs: lint-container
    if: ${{ success() }}

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Get version
        id: python
        run: echo "version=$(cat .python-version)" >> "$GITHUB_OUTPUT"

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          file: ./Dockerfile
          tags: ${{ github.repository }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            REPOSITORY=${{ github.repository }}
            PYTHON_VERSION=${{ steps.python.outputs.version }}

      - name: Run Image
        id: run_image
        uses: addnab/docker-run-action@v3
        with:
          name: test
          image: ${{ github.repository }}:latest
          options: -d -p 8080:8080
          env: |
            NGINX_PORT=8080
            NGINX_HOST=test

      - name: Wait for web server to be ready
        uses: jakejarvis/wait-action@v1
        with:
          timeout: 10
          url: http://localhost:8080

      - name: Test web server is running
        run: |
          test "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)" = "200" || exit 1

      - name: Clean up Docker container
        if: always() && steps.run_image.outcome == 'success'
        run: |
          docker stop test
          docker rm test
